language: node_js

node_js:
  - 'node'
  - 10

install:
  - npm i -g yarn@latest
  - yarn install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules

after_success: codecov
